import './globals.css'
import type { Metadata } from 'next'
import { Inter, Raleway } from 'next/font/google'
import {ReactQueryProvider} from './ReactQueryProvider'
//import { Analytics } from '@vercel/analytics/react';
import AuthProvider from './AuthProvider'

import Navbar from './Navbar'
import Footer from './Footer'

const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'ResumAI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
			<html lang="en" className="bg-white">
				<body className={raleway.className}>
          <AuthProvider>
					<Navbar />
					{children}
          {/*<Analytics />*/}
					<Footer />
          </AuthProvider>
				</body>
			</html>
		</ReactQueryProvider>
  )
}
